#!/bin/bash
gzip -f /usr/local/man/man1/chonos-log.1
mandb

systemctl daemon-reload
systemctl enable chonos-log.service
systemctl enable stunnel4

if [ -d /run/systemd/system ]; then
    systemctl start  chonos-log.service
    systemctl start stunnel4
fi